twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        navigation: '@App\Service\Page\Navigation'
        app_domain: '%app.domain%'
        googleKey: '%env(GOOGLE_API)%'
