version: "3.8"
volumes:
  mysql-data:
services:
  php:
    ports:
      - "8080:80"
#    entrypoint: /usr/bin/app.sh
    build:
      context: .
      dockerfile: ./environment/Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/var/cache

  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: shop
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: hardware-shop
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql